from python:3.11-slim

WORKDIR gigtag
copy backend/requirements.txt .

run pip install --upgrade pip
run pip install -r requirements.txt
run apt update
run apt install -y curl 
RUN curl https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc
RUN curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list |  tee /etc/apt/sources.list.d/mssql-release.list
run apt update
run ACCEPT_EULA=Y apt install -y cron bsdmainutils msodbcsql18
# RUN  apt-get install -y 
# RUN ACCEPT_EULA=Y apt-get install -y mssql-tools18

copy duck.cron .
run crontab duck.cron
run mkdir -p /root/duckdns
copy duck.sh /root/duckdns/duck.sh

COPY dehydrated dehydrated
COPY domains.txt .
COPY get_and_set_certs.sh .
COPY config .
COPY dehydrated_hook.sh .

# echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc
# source ~/.bashrc
# optional: for unixODBC development headers
# sudo apt-get install -y unixodbc-dev
EXPOSE 8120
cmd cron && bash get_and_set_certs.sh && python run.py

copy backend .

# --platform linux/arm64/v8
