from python:3.11-slim

WORKDIR gigtag
copy backend/requirements.txt .

run pip install --upgrade pip
run pip install -r requirements.txt
run apt update
run apt install -y cron curl bsdmainutils

copy duck.cron .
run crontab duck.cron
run mkdir -p /root/duckdns
copy duck.sh /root/duckdns/duck.sh

COPY dehydrated dehydrated
COPY domains.txt .
COPY get_and_set_certs.sh .
COPY config .
COPY dehydrated_hook.sh .

EXPOSE 8120
cmd cron && bash get_and_set_certs.sh && python run.py

copy backend .

# --platform linux/arm64/v8
